# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f816bc64ed308de5b5360c8910f4f857952f7d0960237e4557f529c099f400e7cf6606c0e9f304756bac414b1f9c0c26b8b218ca07eb1ad10c207d0284a0d78d
  twilio_api_token: "84a49be88138c72740f9f7f4db4b69be"
  twilio_sid: "ACd545c43b8144c51c1a2e139d5ab00827"

test:
  secret_key_base: c617c75bbada8a826ca06adcbb4e813682c0f41166ef15d53967783fcb916f6c0bb5cb220355a6bcb5e14c79ad3030954c225bae64e254a553ca2cc1e88026d2
  twilio_api_token: "84a49be88138c72740f9f7f4db4b69be"
  twilio_sid: "ACd545c43b8144c51c1a2e139d5ab00827"

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twilio_api_token: <%= ENV["twilio_api_token"] %>
  twilio_sid: <%= ENV["twilio_sid"] %>
